FROM ghcr.io/mend/renovate-ce:15.1.0@sha256:4f25639e1b5355321e1fefbab55177d1c103697ddb04abbce87e262456f4ce96

COPY renovate.config.cjs /usr/src/app/config.js

ENV RENOVATE_CONFIG_FILE=/usr/src/app/config.js
