FROM ghcr.io/mend/renovate-ce:15.7.0@sha256:2f919312b1251e73de399af93c61019c6d0700ed02bcee4c4aa7ecbb51e3b3ef

USER root

RUN install-tool node 24.20.0
RUN npm install --global codemod@1.17.3
RUN cp --recursive /opt/containerbase/tools/node/24.20.0/lib/node_modules/codemod /opt/codemod
RUN ln --symbolic /opt/codemod/codemod /usr/local/bin/codemod

COPY codemods /usr/src/app/codemods
COPY renovate.config.cjs /usr/src/app/config.js

USER 12021

ENV RENOVATE_CONFIG_FILE=/usr/src/app/config.js
